# project information
site_name: EnglishPal
site_author: Yanchao Wang, Jianhao Zhan, Jiawei Tang, Zhiyuan Chen

# Repository
repo_name: EnglishPal/lab_docs_mkdocs
repo_url: https://github.com/stellafull/EnglishPal
edit_uri: ""

# copyright
copyright: 'Copyright &copy; 2021 Yanchao Wang, Jianhao Zhan, Jiawei Tang, Zhiyuan Chen'

nav: 
    - Home: index.md
    - Lab1: lab1.md
    - Lab2: lab2.md
    - Lab3: lab3.md
theme: 
   name: material
   favicon: img/favicon.ico
   logo: img/favicon.ico
   palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
    - search
    - pdf-export:
        verbose: false
        media_type: print
markdown_extensions:
    - codehilite:
        linenums: true
    - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
extra_javascript:
    - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js


