site_name: EnglishPal
nav: 
    - Home: index.md
    - Lab1: lab1.md
    - Lab2: lab2.md
theme: material

plugins:
    - search
    - mermaid2
extra_javascript:
    - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
